### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by psi-4ward** [alem0lars/vim-colorscheme-darcula#1]
* downloaded it into vim colors folder
* used it via `color darcula` - nothing is colord
* `syntax on` brings an error "Darcula" not found
* changed the name to `let g:colors_name = "darcula"`
* `syntax on` still brings no colors

Vim 7.4.52 on Ubuntu

**Comment by alem0lars** [comment]
```VimL
let g:colors_name = "Darcula"
```
