### ISSUE TITLE
README lacks a screenshot

### ISSUE THREAD

**Issue by pitchforks** [alem0lars/vim-colorscheme-darcula#4]
subj

**Comment by alem0lars** [comment]
Make a pull request ;)

**Comment by pitchforks** [comment]
I really did not mean it as joke or troll issue. It is common for syntax highlight theme repos and vim plugins as well to have screenshots - this is the best advertisement. You don't expect me to go get a Jetbrains product just to see how this syntax highlight theme looks, do you?

If you feel this issue not adequate - feel free to close it.

**Comment by pitchforks** [comment]
Nvm, there's a screenshot for php attached to issue 2. Perhaps you can just use that one?

**Comment by alem0lars** [comment]
This is not intended to be a joke. You've stated that you like some screenshots in the land page and I agree with you.
If you want to take care of making screenshots I'm happy to accept a pull request (if screenshots are adequate).
I don't see any joke here. Do you?

**Comment by pitchforks** [comment]
Uploaded a screenshot here https://img.bi/#/E4LYuZc!92iieQHzplaAL0pFWg2XM_jQ8J730QRVRclQdyd0

**Comment by alessandro-molari** [comment]
Added
